In [17]:
import pandas as pd 


data = pd.read_csv("netflix_titles-selected-columns.csv")
print(data.shape)
data.info()
data.head()

(8807, 10)
<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
dtypes: int64(1), str(9)
memory usage: 688.2 KB

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons

In [10]:
cleaned_data = data.dropna()
cleaned_data.info()
cleaned_data.head()

<class 'pandas.DataFrame'>
Index: 5332 entries, 7 to 8806
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       5332 non-null   str
 1   type          5332 non-null   str
 2   title         5332 non-null   str
 3   director      5332 non-null   str
 4   cast          5332 non-null   str
 5   country       5332 non-null   str
 6   date_added    5332 non-null   str
 7   release_year  5332 non-null   int64
 8   rating        5332 non-null   str
 9   duration      5332 non-null   str
dtypes: int64(1), str(9)
memory usage: 458.2 KB

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min
24,s25,Movie,Jeans,S. Shankar,"Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi...",India,"September 21, 2021",1998,TV-14,166 min

In [29]:
# data['date_added'] = pd.to_datetime(data['date_added'].str.strip(),   format="%B %d, %Y")
data["release_year"] = pd.to_numeric(
    data["release_year"],
    errors="coerce"
)
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
0,S1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,Pg-13,90 Min
1,S2,Tv Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,Tv-Ma,2 Seasons
2,S3,Tv Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,Tv-Ma,1 Season
3,S4,Tv Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,Tv-Ma,1 Season
4,S5,Tv Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,Tv-Ma,2 Seasons
...,...,...,...,...,...,...,...,...,...,...
8802,S8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 Min
8803,S8804,Tv Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,Tv-Y7,2 Seasons
8804,S8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 Min
8805,S8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,Pg,88 Min
8806,S8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,Tv-14,111 Min

In [31]:
text_cols = data.select_dtypes(include="str").columns

data[text_cols] = data[text_cols].apply(
    lambda x: x.str.strip().str.title()
)

In [32]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
0,S1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,Pg-13,90 Min
1,S2,Tv Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,Tv-Ma,2 Seasons
2,S3,Tv Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,Tv-Ma,1 Season
3,S4,Tv Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,Tv-Ma,1 Season
4,S5,Tv Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,Tv-Ma,2 Seasons

In [24]:
fresh_data = data.drop_duplicates()
print(fresh_data.shape)

(8807, 10)

In [36]:
data.sort_values("release_year", ascending=False)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
1,S2,Tv Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,Tv-Ma,2 Seasons
2,S3,Tv Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,Tv-Ma,1 Season
3,S4,Tv Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,Tv-Ma,1 Season
31,S32,Tv Show,Chicago Party Aunt,NaN,"Lauren Ash, Rory O'Malley, Rupaul Charles, Jil...",NaN,"September 17, 2021",2021,Tv-Ma,1 Season
30,S31,Movie,Ankahi Kahaniya,"Ashwiny Iyer Tiwari, Abhishek Chaubey, Saket C...","Abhishek Banerjee, Rinku Rajguru, Delzad Hiwal...",NaN,"September 17, 2021",2021,Tv-14,111 Min
...,...,...,...,...,...,...,...,...,...,...
8739,S8740,Movie,Why We Fight: The Battle Of Russia,"Frank Capra, Anatole Litvak",NaN,United States,"March 31, 2017",1943,Tv-Pg,82 Min
8660,S8661,Movie,Undercover: How To Operate Behind Enemy Lines,John Ford,NaN,United States,"March 31, 2017",1943,Tv-Pg,61 Min
7790,S7791,Movie,Prelude To War,Frank Capra,NaN,United States,"March 31, 2017",1942,Tv-14,52 Min
8205,S8206,Movie,The Battle Of Midway,John Ford,"Henry Fonda, Jane Darwell",United States,"March 31, 2017",1942,Tv-14,18 Min
4250,S4251,Tv Show,Pioneers: First Women Filmmakers*,NaN,NaN,NaN,"December 30, 2018",1925,Tv-14,1 Season

In [37]:
data.isna().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
dtype: int64

In [38]:
data.duplicated().sum()

np.int64(0)

In [42]:
unique_id = data[data['show_id'].astype(str).str.endswith("7")]

unique_id.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration
6,S7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,Pg,91 Min
16,S17,Movie,Europe'S Most Dangerous Man: Otto Skorzeny In ...,"Pedro De Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,Tv-Ma,67 Min
26,S27,Movie,Minsara Kanavu,Rajiv Menon,"Arvind Swamy, Kajol, Prabhu Deva, Nassar, S.P....",NaN,"September 21, 2021",1997,Tv-Pg,147 Min
36,S37,Movie,The Stronghold,Cédric Jimenez,"Gilles Lellouche, Karim Leklou, François Civil...",NaN,"September 17, 2021",2021,Tv-Ma,105 Min
46,S47,Movie,Safe House,Daniel Espinosa,"Denzel Washington, Ryan Reynolds, Vera Farmiga...","South Africa, United States, Japan","September 16, 2021",2012,R,115 Min